### PR TITLE
Add `zones_directory` variable to map

### PR DESCRIPTION
**Pull request by ryanwalder**
* This allows the `named_directory` to be the base bind directory as it should so it can be used as a base variable for other directories. Then use the `zones_directory` for placing the zone files in.

* Change zonefile include to use absolute path

### CODE REVIEW

**Comment by ryanwalder** [comment]
Just realized I submitted this without running the tests, running them now.

**Comment by ryanwalder** [comment]
Well the debian/ubuntu tests are working. The Fedora/CentOS ones are failing... 
Looking into it now.

**Comment by ryanwalder** [comment]
There we go all tests passing now.

This should be good to merge onto your branch then merge into upstream (assuming you agree with my changes!).

**Review by joe-bowman — COMMENTED** [review]
lgtm.

**Pull request merged**
